### ISSUE TITLE
Unable to install django-mirage-field in Windows machine

### ISSUE THREAD

**Issue by manishakeim** [luojilab/django-mirage-field#12]
Facing the following error(UnicodeDecodeError) while installing django-mirage-field:

![image](https://user-images.githubusercontent.com/10472556/102871246-33b74800-4464-11eb-9ae7-4cb2d8db0bbb.png)

**Comment by tcitry** [comment]
@manishakeim Thanks for your report.

I refered to [StackOverflow](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character) and fixed in 58088ed , check in version [1.1.7](https://pypi.org/project/django-mirage-field/1.1.7/), please let me know if this commit does not work.

**Comment by manishakeim** [comment]
Thanks, @tcitry. It solved the issue.
